import { StyleSheet } from 'react-native';
import { scale, verticalScale, moderateScale } from '../../utils/responsive';
import { AppSizes } from '../../utils/AppSizes';

export const helpSupportStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerTitle: {
    alignSelf: 'center',
    fontSize: AppSizes.FONT_22,
    fontFamily: 'PlusJakartaSans-Bold',
    marginBottom: scale(4),
  },
  scrollContent: {
    padding: scale(16),
    paddingBottom: scale(40),
    flexGrow: 1,
    // justifyContent: 'center',
    marginTop: scale(20),
  },
  banner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderRadius: scale(14),
    padding: scale(16),
    marginBottom: scale(20),
  },
  bannerTitle: {
    fontSize: AppSizes.FONT_16,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  bannerText: {
    fontSize: moderateScale(13),
    fontFamily: 'PlusJakartaSans-Regular',
    marginTop: verticalScale(3),
    lineHeight: moderateScale(18),
  },
  sectionTitle: {
    fontSize: moderateScale(15),
    fontFamily: 'PlusJakartaSans-SemiBold',
    marginBottom: scale(10),
    marginTop: scale(4),
  },
  contactCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: scale(14),
    padding: scale(14),
    marginBottom: scale(10),
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },
  contactIconBox: {
    width: scale(40),
    height: AppSizes.H_40,
    borderRadius: AppSizes.RADIUS_12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contactTitle: {
    fontSize: AppSizes.FONT_14,
    fontFamily: 'PlusJakartaSans-Medium',
  },
  contactSubtitle: {
    fontSize: AppSizes.FONT_12,
    fontFamily: 'PlusJakartaSans-Regular',
    marginTop: AppSizes.MV_2,
  },
  faqCard: {
    borderRadius: scale(14),
    padding: scale(14),
    marginBottom: scale(10),
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
  },
  faqHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(10),
  },
  faqQuestion: {
    flex: 1,
    fontSize: moderateScale(13),
    fontFamily: 'PlusJakartaSans-Medium',
  },
  faqAnswer: {
    fontSize: moderateScale(13),
    fontFamily: 'PlusJakartaSans-Regular',
    marginTop: scale(10),
    lineHeight: moderateScale(19),
  },
  reportCard: {
    borderRadius: scale(14),
    padding: scale(16),
    marginBottom: scale(10),
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
  },
  fieldLabel: {
    fontSize: moderateScale(13),
    fontFamily: 'PlusJakartaSans-Medium',
    marginBottom: scale(6),
  },
  textInput: {
    borderWidth: 1,
    borderRadius: AppSizes.RADIUS_10,
    paddingHorizontal: scale(14),
    paddingVertical: scale(12),
    fontSize: AppSizes.FONT_14,
    fontFamily: 'PlusJakartaSans-Regular',
  },
  textArea: {
    minHeight: verticalScale(90),
    textAlignVertical: 'top',
  },
  sendButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: scale(8),
    borderRadius: AppSizes.RADIUS_10,
    paddingVertical: verticalScale(13),
    marginTop: scale(16),
  },
  sendButtonText: {
    color: '#fff',
    fontSize: AppSizes.FONT_14,
    fontFamily: 'PlusJakartaSans-SemiBold',
  },
});
